rm(list = ls())
(x <- "alfa,bravo,charlie,delta")
strsplit(x, split = ",")
unlist(strsplit(x, split = ","))
strsplit(x, split = ",")[[1]]

strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}

use_r("strsplit1")

library(devtools)
use_git()
use_github()
load_all()
(x <- "alfa,bravo,charlie,delta")
#> [1] "alfa,bravo,charlie,delta"
strsplit1(x, split = ",")
#> [1] "alfa"    "bravo"   "charlie" "delta"
#>
exists("strsplit1", where = globalenv(), inherits = FALSE)
#> [1] FALSE
check()

install()

## licence
use_mit_license()
#> ✔ Adding "MIT + file LICENSE" to 'License'.
#> ✔ Writing 'LICENSE'.
#> ✔ Writing 'LICENSE.md'.
#> ✔ Adding "^LICENSE\\.md$" to '.Rbuildignore'.
#>
#>
document()

# Generated by roxygen2: do not edit by hand

export(strsplit1)


use_testthat()
#> ✔ Adding testthat to 'Suggests' field in DESCRIPTION.
#> ✔ Adding "3" to 'Config/testthat/edition'.
#> ✔ Creating 'tests/testthat/'.
#> ✔ Writing 'tests/testthat.R'.
#> ☐ Call `usethis::use_test()` to initialize a basic test file and
#>   open it for editing.
#>
use_test("strsplit1")
#> ✔ Writing 'tests/testthat/test-strsplit1.R'.
#> ☐ Edit 'tests/testthat/test-strsplit1.R'.
#>

test()
#> ℹ Testing regexcite
#> ✔ | F W  S  OK | Context
#>
#> ⠏ |          0 | strsplit1
#> ✔ |          1 | strsplit1
#>
#> ══ Results ═════════════════════════════════════════════════════════
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ]

use_package("stringr")
#> ✔ Adding stringr to 'Imports' field in DESCRIPTION.
#> ☐ Refer to functions with `stringr::fun()`.
rename_files("strsplit1", "str_split_one")
